version: '3'
services:
  dcard:
    build: .
    restart: always
    environment:
      - token=x
      - channel_id=x
      - tdc=x
    links:
      - redis
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - /home/tsai/dcardboardcast/redisdata/:/data